### PR TITLE
StructReflection & Columns

### PR DESCRIPTION
**Pull request by gzanitti**
This PR:
- Adds [struct-reflections-rs](https://github.com/gzanitti/struct-reflection-rs) to get the column names.
- Implements the columns() method in all `BaseAir` (based on changes introduced in https://github.com/gzanitti/Plonky3/pull/1)

### CODE REVIEW

File: crates/vm/src/arch/integration_api.rs [hunk 1]
```diff
@@ -360,6 +360,18 @@ where
...
+    fn columns(&self) -> Option<Vec<String>> {
+        let combined_columns = self
+            .adapter
+            .columns()
+            .into_iter()
+            .flatten()
+            .chain(self.core.columns().into_iter().flatten())
+            .collect::<Vec<_>>();
+
+        (!combined_columns.is_empty()).then_some(combined_columns)
```
Comment (georgwiese) [inline crates/vm/src/arch/integration_api.rs:373]:
```suggestion
        if let (Some(adapter_columns), Some(core_columns)) = (self.adapter.columns(), self.core.columns()) {
            Some(adapter_columns.into_iter().chain(core_columns).collect())
        } else {
            None
        }
```

I think something like this (haven't tested it) would be more correct: We want to return `Some(_)` iff. both the core and adapter return `Some(_)`.

File: crates/vm/src/system/public_values/core.rs [hunk 2]
```diff
@@ -42,6 +42,10 @@ impl<F: Field> BaseAir<F> for PublicValuesCoreAir {
     fn width(&self) -> usize {
         3 + self.encoder.width()
     }
+
+    fn columns(&self) -> Option<Vec<String>> {
+        todo!("Vec<T> does not implement StructReflection (PublicValuesCoreCols)")
```
Comment (georgwiese) [inline crates/vm/src/system/public_values/core.rs:47]: I think returning `None` would be better, so we can still export the PIL without column names.

File: rust-toolchain.toml [hunk 3]
```diff
@@ -1,3 +1,3 @@
 [toolchain]
-channel = "nightly-2024-10-30"     # "1.82.0"
+channel = "nightly-2024-12-16"     # "1.82.0"
```
Comment (georgwiese) [inline rust-toolchain.toml:2]: Why is this necessary? I think in the interest of being able to potentially upstream these changes, I think we should avoid changing the Rust version if possible.

**Comment by georgwiese** [comment]
Also, the [struct-reflections-rs](https://github.com/gzanitti/struct-reflection-rs) repo looks nice! :)

File: Cargo.toml [hunk 4]
```diff
@@ -193,6 +193,7 @@ snark-verifier-sdk = { git = "https://github.com/axiom-crypto/snark-verifier", b
 ] }
 zkhash = { git = "https://github.com/HorizenLabs/poseidon2.git", rev = "bb476b9" }
 halo2curves-axiom = "0.5.3"
+struct-reflection = { git = "https://github.com/gzanitti/struct-reflection-rs.git" }
```
[the remark this answers is not in the document]
Comment (gzanitti) [reply Cargo.toml:196]: Yes, and maybe we should also move it to a powdr/Plonky3 repo?

[the remark this answers is not in the document]
Comment (georgwiese) [reply Cargo.toml:196]: I discussed this with @leonardoalt briefly, and we agreed that for now it's fine like that and mid-term he noted that it might be difficult to up-stream the changes if we need to fork Plonky3. So, we might have to change it again, maybe by adding our own trait, or going back to using one of OpenVMs...

But I think this is a problem for a later time. It makes a lot of sense to me that the `columns()` function would be next to the `width()` function (one could even be implemented in terms of the other).

[the remark this answers is not in the document]
Comment (gzanitti) [reply Cargo.toml:196]: What about adding a Column trait and move all the implementations that we need there, so we can merge and use this without the dependencies, at least for now?

[the remark this answers is not in the document]
Comment (georgwiese) [reply Cargo.toml:196]: Sure also works!

[the remark this answers is not in the document]
Comment (gzanitti) [reply Cargo.toml:196]: This PR no longer requires Plonky3 nor does it have any duplicate code within openvm. However, it imposes a small constraint that I'm not sure will be accepted upstream. More here: https://github.com/powdr-labs/stark-backend/pull/3/files#r2018748311

**Review by georgwiese — COMMENTED** [review]
Nice! This looks good to me. But I think we have to merge https://github.com/powdr-labs/stark-backend/pull/3 first or do what I suggested in [this comment](https://github.com/powdr-labs/stark-backend/pull/3#discussion_r2021131750) (which would require changes in this PR).

**Review by georgwiese — APPROVED** [review]
